### ISSUE TITLE
run script from src tag

### ISSUE THREAD

**Issue by zhex900** [hacke2/vue-append#3]
Hi,

How do I run external javascript with `<script src> </script>`?

https://github.com/hacke2/vue-append/blob/3206e31ca2250588fbb51cf471c907d0ad05ed89/vue-append.js#L65-L66

I guess I want something like this. This code downloads the script and insert it into the DOM. Its pretty ugly code. It works for now. 

             if (el.src && el.id === 'external_script') {
              var http = new XMLHttpRequest();
              http.open('GET', el.src, true);
              http.onreadystatechange = function () {
                if (http.readyState === 4) {
                  // Makes sure the document is ready to parse.
                  if (http.status === 200) {
                    el.innerHTML = http.responseText;
                    setTimeout(function () {
                      var target = el.ownerDocument ?
                        el.ownerDocument.defaultView :
                        window;
                      target['eval'].call(target, el.innerHTML);
                    });
                  }
                }
              };
              http.send(null);
            } else {

              setTimeout(function () {
                var target = el.ownerDocument ?
                  el.ownerDocument.defaultView :
                  window;
                target['eval'].call(target, el.innerHTML);
              });
            }

**Comment by hacke2** [comment]
can you provide a PR?

**Comment by hacke2** [comment]
Done， Please use 2.0.0

+ vue-append@2.0.0

**Comment by zoey9999** [comment]
![@DE4HMUWA7WO`T(Q01HCFZ3](https://user-images.githubusercontent.com/46919942/77617070-308f3a00-6f6e-11ea-9cc0-93ae1b3be2fd.png)
How to solve this problem?
